### ISSUE TITLE
Add an option to exclude specific components.

### ISSUE THREAD

**Issue by SukkaW** [lxsmnsyc/forgetti#16]
Since `forgetti` is still under active experimentation and development, there might be a case where `forgetti` fails to correctly perform optimization (just like #14).

Thus I'd like to have the option to exclude some specific components so that the rest of the app can still be optimized by `forgetti` while waiting for `forgetti` to fix the issue.

**Comment by lxsmnsyc** [comment]
Welp you've added `@forgetti skip` now
