### ISSUE TITLE
console API should not be cached， it will not execute during re-rendering. 

### ISSUE THREAD

**Issue by jeryqwq** [lxsmnsyc/forgetti#32]
I think `/* @forgetti skip */` config should support  ExpressionStatement  , like 
``` 
 /* @forgetti skip */console.log(done);
```
But now it removes the entire console expression statement.
or if ExpressionStatement is console api ,  cache and _equals should skip console

**Comment by jeryqwq** [comment]
```js
 optimizeExpression(
    path: babel.NodePath<t.Expression>,
  ): OptimizedExpression {
    if (shouldSkipNode(path.node) ||  isConsoleApi(path.node)) {
      // this.scope.push(path.node);
      return optimizedExpr(path.node, undefined, true);
    }
```

**Comment by forgetti** [comment]
Hi. I'm being emailed about this cause my GitHub account shares a name with
your software.

**Comment by lxsmnsyc** [comment]
> Hi. I'm being emailed about this cause my GitHub account shares a name with your software.

Sorry for the inconvenience. It was a mistake on behalf of the thread owner. I've removed your tag and hopefully you can unsubscribe from this thread from further notifications.

@jeryqwq 
With regards to caching `console`, the expression caching is generalized and does not discriminate for `console`, after all, React also overrides it internally. The skip pragma can be a solution although I guess it's still lacking fine-grained configuration. I'll take a look on it.

**Comment by jeryqwq** [comment]
thanks for the effort

**Comment by jeryqwq** [comment]
thanks for the effort，Can we add a configuration to adapt to similar scenarios?
