### ISSUE TITLE
getBooleanishState NumericLiteral wrong return type

### ISSUE THREAD

**Issue by ignatiqq** [lxsmnsyc/forgetti#38]
Hello, in the file "forgetti/src/core/simplify-expressions.ts" we have a helper "getBooleanishState". And there we have a check on "NumericLiteral" test.node, which returns "falsy" only if num is strictly zero. 

<img width="519" alt="image" src="https://github.com/lxsmnsyc/forgetti/assets/89993147/e8f30f61-8832-4880-b27c-c1eef7ac9064">

But shouldn't we return type 'falsy' if num is less than zero?
If it's a bug i can take it.

**Comment by lxsmnsyc** [comment]
![image](https://github.com/lxsmnsyc/forgetti/assets/4783372/13a9de61-fbaf-42e1-a25e-23c5032c5c38)

This should probably summarize it.
