### ISSUE TITLE
Forgetti should ignore specific identifier

### ISSUE THREAD

**Issue by SukkaW** [lxsmnsyc/forgetti#6]
Given input:

```jsx
export default function Example() {
  if (process.env.NODE_ENV === 'production') {
    return <div />;
  }

  if (import.meta.env.DEV) {
    return <h1 />;
  }

  return <br />;
}
```

Forgetti produces:

```jsx
import { jsx as _jsx } from "react/jsx-runtime";
import { useMemo as _useMemo } from "react";
import { $$cache as _$$cache } from "forgetti/runtime";
export default function Example() {
    var _c, _ref, _c1, _ref1, _c2, _ref2, _c3, _ref3, _c4, _ref4;
    let _c5 = _$$cache(_useMemo, 7), _v = (_c = _c5)[_ref = 0] || (_c[_ref] = process.env), _v2 = (_c1 = _c5)[_ref1 = 1] || (_c1[_ref1] = _v.NODE_ENV);
    if (_v2 === 'production') {
        var _c6, _ref5, _c21, _ref6;
        let _c2 = (_c6 = _c5)[_ref5 = 2] || (_c6[_ref5] = new Array(1)), _v3 = (_c21 = _c2)[_ref6 = 0] || (_c21[_ref6] = /*#__PURE__*/ _jsx("div", {}));
        return _v3;
    }
    let _v4 = (_c2 = _c5)[_ref2 = 3] || (_c2[_ref2] = import.meta.env), _v5 = (_c3 = _c5)[_ref3 = 4] || (_c3[_ref3] = _v4.DEV);
    if (_v5) {
        var _c7, _ref7, _c31, _ref8;
        let _c3 = (_c7 = _c5)[_ref7 = 5] || (_c7[_ref7] = new Array(1)), _v6 = (_c31 = _c3)[_ref8 = 0] || (_c31[_ref8] = /*#__PURE__*/ _jsx("h1", {}));
        return _v6;
    }
    let _v7 = (_c4 = _c5)[_ref4 = 6] || (_c4[_ref4] = /*#__PURE__*/ _jsx("br", {}));
    return _v7;
}
```

Where `process.env.NODE_ENV` and `import.meta.env.DEV` are processed by forgetti.

Currently, I am using webpack's `DefinePlugin` to replace `process.env.NODE_ENV` and `import.meta.env.DEV`. In webpack, `DefinePlugin` is executed after loaders (`swc-loaders`, `babel-loaders`, `esbuild-loaders`, etc., and in this case, `forgetti-loader`). `process.env.NODE_ENV` and `import.meta.env.DEV` can no longer be replaced by webpack's `DefinePlugin` after the forgetti transformation.

I propose that forgetti should accept an option to ignore specific identifiers when memoizing.

**Comment by lxsmnsyc** [comment]
hmmm yes, interesting case. It's a bit weird because it needs Forgetti to check first the root source of the member expression (`process` and `import.meta` are the roots) before deciding for optimization. I'll see if there's a workaround.
